import sqlite3
import json
from datetime import datetime, timedelta

def init_db():
    conn = sqlite3.connect('eatwhat.db')
    c = conn.cursor()

    c.execute('''
        CREATE TABLE IF NOT EXISTS recipes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR(100) NOT NULL,
            category VARCHAR(20) NOT NULL,
            ingredients TEXT NOT NULL,
            steps TEXT NOT NULL,
            cost DECIMAL(6,2) NOT NULL,
            difficulty INTEGER NOT NULL,
            gi_value INTEGER NOT NULL,
            cook_time INTEGER NOT NULL,
            nutrition_tags TEXT,
            season VARCHAR(20) DEFAULT 'all',
            calories INTEGER DEFAULT 0,
            protein DECIMAL(5,1) DEFAULT 0,
            carbs DECIMAL(5,1) DEFAULT 0,
            fat DECIMAL(5,1) DEFAULT 0,
            fiber DECIMAL(5,1) DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS weekly_menus (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            menu_data TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            openid VARCHAR(100) UNIQUE NOT NULL,
            nickname VARCHAR(100),
            avatar_url VARCHAR(500),
            settings TEXT,
            preferences TEXT,
            subscribed INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS user_diet_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            openid VARCHAR(100) NOT NULL,
            date DATE NOT NULL,
            meal_type VARCHAR(20) NOT NULL,
            recipe_id INTEGER,
            eaten INTEGER DEFAULT 0,
            notes TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (openid) REFERENCES users(openid),
            FOREIGN KEY (recipe_id) REFERENCES recipes(id)
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS nutrition_stats (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            openid VARCHAR(100) NOT NULL,
            date DATE NOT NULL,
            total_calories DECIMAL(7,1) DEFAULT 0,
            total_protein DECIMAL(6,1) DEFAULT 0,
            total_carbs DECIMAL(6,1) DEFAULT 0,
            total_fat DECIMAL(6,1) DEFAULT 0,
            total_fiber DECIMAL(6,1) DEFAULT 0,
            gi_avg INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (openid) REFERENCES users(openid)
        )
    ''')

    conn.commit()

    if c.execute('SELECT COUNT(*) FROM recipes').fetchone()[0] == 0:
        init_recipes(c)
        conn.commit()

    conn.close()

def init_recipes(c):
    recipes = [
        {
            "name": "小米粥",
            "category": "breakfast",
            "ingredients": json.dumps(["小米:50g", "水:500ml", "枸杞:5g"]),
            "steps": json.dumps(["小米洗净备用", "锅中加水烧开", "放入小米大火煮开", "转小火熬20分钟", "加入枸杞即可"]),
            "cost": 5.0,
            "difficulty": 1,
            "gi_value": 55,
            "cook_time": 25,
            "nutrition_tags": json.dumps(["低GI", "养胃", "简单"]),
            "season": "all",
            "calories": 180,
            "protein": 5.0,
            "carbs": 38.0,
            "fat": 1.5,
            "fiber": 2.0
        },
        {
            "name": "鸡蛋燕麦粥",
            "category": "breakfast",
            "ingredients": json.dumps(["燕麦:40g", "鸡蛋:1个", "牛奶:200ml", "蜂蜜:5g"]),
            "steps": json.dumps(["燕麦加水煮开", "打入鸡蛋搅拌", "加入牛奶稍煮", "关火后加蜂蜜"]),
            "cost": 8.0,
            "difficulty": 1,
            "gi_value": 42,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "减脂"]),
            "season": "all",
            "calories": 280,
            "protein": 15.0,
            "carbs": 35.0,
            "fat": 8.0,
            "fiber": 4.0
        },
        {
            "name": "全麦三明治",
            "category": "breakfast",
            "ingredients": json.dumps(["全麦面包:2片", "鸡蛋:1个", "生菜:2片", "番茄:半个"]),
            "steps": json.dumps(["鸡蛋煎熟", "番茄切片", "面包依次放生菜、番茄、鸡蛋", "合上面包即可"]),
            "cost": 6.0,
            "difficulty": 1,
            "gi_value": 45,
            "cook_time": 10,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "快捷"]),
            "season": "all",
            "calories": 220,
            "protein": 12.0,
            "carbs": 28.0,
            "fat": 8.0,
            "fiber": 5.0
        },
        {
            "name": "玉米糊",
            "category": "breakfast",
            "ingredients": json.dumps(["玉米面:30g", "水:300ml", "盐:1g"]),
            "steps": json.dumps(["玉米面加水调匀", "锅中烧水", "倒入玉米面水不停搅拌", "煮开即可"]),
            "cost": 3.0,
            "difficulty": 1,
            "gi_value": 48,
            "cook_time": 10,
            "nutrition_tags": json.dumps(["低GI", "粗粮", "简单"]),
            "season": "all",
            "calories": 120,
            "protein": 3.0,
            "carbs": 25.0,
            "fat": 1.0,
            "fiber": 2.0
        },
        {
            "name": "菠菜鸡蛋汤",
            "category": "breakfast",
            "ingredients": json.dumps(["菠菜:100g", "鸡蛋:1个", "盐:2g", "香油:3ml"]),
            "steps": json.dumps(["菠菜洗净切段", "锅中烧水", "水开打入鸡蛋", "放入菠菜煮沸", "加盐香油调味"]),
            "cost": 5.0,
            "difficulty": 1,
            "gi_value": 15,
            "cook_time": 10,
            "nutrition_tags": json.dumps(["低GI", "富含铁", "清爽"]),
            "season": "all",
            "calories": 130,
            "protein": 10.0,
            "carbs": 5.0,
            "fat": 8.0,
            "fiber": 3.0
        },
        {
            "name": "番茄炒蛋",
            "category": "lunch",
            "ingredients": json.dumps(["番茄:2个", "鸡蛋:2个", "油:10ml", "盐:2g", "糖:3g"]),
            "steps": json.dumps(["番茄切块", "鸡蛋打散加少许盐", "热油炒鸡蛋盛出", "另起油炒番茄出汁", "加入鸡蛋翻炒", "加盐糖调味"]),
            "cost": 10.0,
            "difficulty": 1,
            "gi_value": 20,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "维C丰富", "家常"]),
            "season": "all",
            "calories": 220,
            "protein": 14.0,
            "carbs": 15.0,
            "fat": 12.0,
            "fiber": 3.0
        },
        {
            "name": "清炒西兰花",
            "category": "lunch",
            "ingredients": json.dumps(["西兰花:200g", "蒜:3瓣", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["西兰花切小朵洗净", "蒜切末", "热油爆香蒜末", "放入西兰花翻炒", "加少许水焖煮", "加盐调味"]),
            "cost": 8.0,
            "difficulty": 1,
            "gi_value": 15,
            "cook_time": 12,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "抗癌"]),
            "season": "all",
            "calories": 150,
            "protein": 6.0,
            "carbs": 12.0,
            "fat": 9.0,
            "fiber": 6.0
        },
        {
            "name": "糙米饭",
            "category": "lunch",
            "ingredients": json.dumps(["糙米:100g", "水:200ml"]),
            "steps": json.dumps(["糙米提前浸泡2小时", "放入电饭煲", "加水煮熟"]),
            "cost": 4.0,
            "difficulty": 1,
            "gi_value": 50,
            "cook_time": 45,
            "nutrition_tags": json.dumps(["低GI", "粗粮", "饱腹"]),
            "season": "all",
            "calories": 180,
            "protein": 4.0,
            "carbs": 38.0,
            "fat": 1.5,
            "fiber": 3.5
        },
        {
            "name": "鸡胸肉沙拉",
            "category": "lunch",
            "ingredients": json.dumps(["鸡胸肉:100g", "生菜:50g", "黄瓜:50g", "番茄:50g", "橄榄油:5ml", "柠檬汁:10ml"]),
            "steps": json.dumps(["鸡胸肉煮熟撕成丝", "生菜黄瓜番茄洗净切好", "混合蔬菜和鸡肉", "淋上橄榄油柠檬汁"]),
            "cost": 18.0,
            "difficulty": 2,
            "gi_value": 20,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "减脂", "清爽"]),
            "season": "summer",
            "calories": 250,
            "protein": 32.0,
            "carbs": 10.0,
            "fat": 10.0,
            "fiber": 4.0
        },
        {
            "name": "红烧豆腐",
            "category": "lunch",
            "ingredients": json.dumps(["豆腐:200g", "生抽:10ml", "糖:5g", "葱:5g", "油:10ml"]),
            "steps": json.dumps(["豆腐切块", "热油煎至两面金黄", "加生抽糖调味", "加水焖煮", "撒葱花出锅"]),
            "cost": 8.0,
            "difficulty": 2,
            "gi_value": 15,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["低GI", "植物蛋白", "补钙"]),
            "season": "all",
            "calories": 200,
            "protein": 15.0,
            "carbs": 12.0,
            "fat": 10.0,
            "fiber": 2.0
        },
        {
            "name": "番茄牛腩面",
            "category": "lunch",
            "ingredients": json.dumps(["牛腩:100g", "番茄:2个", "面条:100g", "洋葱:半个", "盐:3g"]),
            "steps": json.dumps(["牛腩切块焯水", "番茄洋葱切块", "先炒牛腩加水炖1小时", "另煮面", "牛腩汤加番茄煮开", "拌面食用"]),
            "cost": 30.0,
            "difficulty": 3,
            "gi_value": 35,
            "cook_time": 90,
            "nutrition_tags": json.dumps(["高蛋白", "暖身", "家常"]),
            "season": "winter",
            "calories": 450,
            "protein": 28.0,
            "carbs": 55.0,
            "fat": 14.0,
            "fiber": 4.0
        },
        {
            "name": "清蒸鲈鱼",
            "category": "dinner",
            "ingredients": json.dumps(["鲈鱼:200g", "姜:5g", "葱:5g", "蒸鱼豉油:15ml"]),
            "steps": json.dumps(["鲈鱼洗净划刀", "姜丝葱段铺在鱼上", "大火蒸10分钟", "取出倒掉汤汁", "淋上蒸鱼豉油", "热油浇鱼"]),
            "cost": 25.0,
            "difficulty": 2,
            "gi_value": 0,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "鲜嫩", "少油"]),
            "season": "all",
            "calories": 180,
            "protein": 35.0,
            "carbs": 3.0,
            "fat": 4.0,
            "fiber": 0.5
        },
        {
            "name": "蒜蓉青菜",
            "category": "dinner",
            "ingredients": json.dumps(["青菜:200g", "蒜:5g", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["青菜洗净", "蒜切末", "热油爆香蒜末", "放入青菜大火翻炒", "加盐调味即可"]),
            "cost": 5.0,
            "difficulty": 1,
            "gi_value": 15,
            "cook_time": 8,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "清爽", "简单"]),
            "season": "all",
            "calories": 100,
            "protein": 3.0,
            "carbs": 8.0,
            "fat": 6.0,
            "fiber": 4.0
        },
        {
            "name": "紫薯粥",
            "category": "dinner",
            "ingredients": json.dumps(["紫薯:100g", "大米:50g", "水:500ml"]),
            "steps": json.dumps(["紫薯去皮切块", "大米洗净", "一起放入锅中加水", "煮至粥稠即可"]),
            "cost": 6.0,
            "difficulty": 1,
            "gi_value": 45,
            "cook_time": 40,
            "nutrition_tags": json.dumps(["低GI", "花青素", "粗粮"]),
            "season": "all",
            "calories": 200,
            "protein": 4.0,
            "carbs": 45.0,
            "fat": 1.0,
            "fiber": 3.0
        },
        {
            "name": "凉拌黄瓜",
            "category": "dinner",
            "ingredients": json.dumps(["黄瓜:200g", "蒜:3g", "醋:10ml", "香油:3ml", "盐:2g"]),
            "steps": json.dumps(["黄瓜拍碎切块", "蒜切末", "加醋香油盐拌匀", "冰箱冷藏10分钟味道更佳"]),
            "cost": 4.0,
            "difficulty": 1,
            "gi_value": 10,
            "cook_time": 10,
            "nutrition_tags": json.dumps(["低GI", "解暑", "爽口", "简单"]),
            "season": "summer",
            "calories": 80,
            "protein": 2.0,
            "carbs": 6.0,
            "fat": 4.0,
            "fiber": 2.0
        },
        {
            "name": "番茄鸡蛋面",
            "category": "dinner",
            "ingredients": json.dumps(["番茄:1个", "鸡蛋:1个", "面条:80g", "葱:3g", "盐:2g"]),
            "steps": json.dumps(["番茄切块", "鸡蛋打散", "煮面条至八成熟", "另起锅炒番茄鸡蛋", "加水煮开", "放入面条撒葱花"]),
            "cost": 10.0,
            "difficulty": 1,
            "gi_value": 30,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["低GI", "快捷", "家常"]),
            "season": "all",
            "calories": 320,
            "protein": 14.0,
            "carbs": 48.0,
            "fat": 8.0,
            "fiber": 3.0
        },
        {
            "name": "虾仁豆腐羹",
            "category": "dinner",
            "ingredients": json.dumps(["虾仁:50g", "豆腐:100g", "鸡蛋:1个", "葱:3g", "盐:2g", "淀粉:5g"]),
            "steps": json.dumps(["虾仁洗净", "豆腐切块", "锅中加水烧开", "放入虾仁豆腐", "鸡蛋打散倒入", "水淀粉勾芡", "加盐葱花调味"]),
            "cost": 15.0,
            "difficulty": 2,
            "gi_value": 15,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "补钙", "鲜美"]),
            "season": "all",
            "calories": 200,
            "protein": 22.0,
            "carbs": 8.0,
            "fat": 9.0,
            "fiber": 1.0
        },
        {
            "name": "清炒藕片",
            "category": "dinner",
            "ingredients": json.dumps(["莲藕:150g", "蒜:3g", "葱:3g", "油:10ml", "盐:2g", "醋:5ml"]),
            "steps": json.dumps(["莲藕去皮切片", "泡水中防氧化", "热油爆香蒜葱", "捞出藕片翻炒", "加醋盐调味", "快速出锅保持脆感"]),
            "cost": 8.0,
            "difficulty": 1,
            "gi_value": 30,
            "cook_time": 10,
            "nutrition_tags": json.dumps(["低GI", "清热", "爽脆"]),
            "season": "summer",
            "calories": 140,
            "protein": 3.0,
            "carbs": 22.0,
            "fat": 5.0,
            "fiber": 3.0
        },
        {
            "name": "山药排骨汤",
            "category": "dinner",
            "ingredients": json.dumps(["排骨:150g", "山药:100g", "枸杞:5g", "姜:3g", "盐:2g"]),
            "steps": json.dumps(["排骨焯水", "山药切块", "排骨山药姜片入锅", "加水炖1.5小时", "加枸杞盐调味"]),
            "cost": 35.0,
            "difficulty": 2,
            "gi_value": 20,
            "cook_time": 100,
            "nutrition_tags": json.dumps(["高蛋白", "滋补", "养胃", "暖身"]),
            "season": "winter",
            "calories": 350,
            "protein": 25.0,
            "carbs": 18.0,
            "fat": 20.0,
            "fiber": 2.0
        },
        {
            "name": "木耳炒肉",
            "category": "dinner",
            "ingredients": json.dumps(["木耳:50g", "瘦肉:100g", "青椒:50g", "蒜:3g", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["木耳泡发撕小朵", "瘦肉切片", "青椒切块", "热油炒肉片", "加木耳青椒翻炒", "加盐调味"]),
            "cost": 15.0,
            "difficulty": 1,
            "gi_value": 25,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "补铁", "清血管"]),
            "season": "all",
            "calories": 220,
            "protein": 20.0,
            "carbs": 10.0,
            "fat": 12.0,
            "fiber": 5.0
        },
        {
            "name": "薏米红豆粥",
            "category": "breakfast",
            "ingredients": json.dumps(["薏米:30g", "红豆:30g", "水:600ml", "冰糖:10g"]),
            "steps": json.dumps(["薏米红豆提前浸泡4小时", "放入锅中加水", "大火煮开转小火", "熬至软烂加冰糖"]),
            "cost": 8.0,
            "difficulty": 1,
            "gi_value": 40,
            "cook_time": 60,
            "nutrition_tags": json.dumps(["低GI", "祛湿", "美容", "粗粮"]),
            "season": "all",
            "calories": 220,
            "protein": 8.0,
            "carbs": 42.0,
            "fat": 2.0,
            "fiber": 5.0
        },
        {
            "name": "鸡蛋葱油饼",
            "category": "breakfast",
            "ingredients": json.dumps(["面粉:100g", "鸡蛋:1个", "葱:10g", "油:15ml", "盐:2g"]),
            "steps": json.dumps(["面粉加水揉成面团", "擀成薄饼", "刷油撒葱花盐", "卷起再擀开", "平底锅烙至金黄", "打蛋翻面烙熟"]),
            "cost": 6.0,
            "difficulty": 2,
            "gi_value": 55,
            "cook_time": 25,
            "nutrition_tags": json.dumps(["家常", "饱腹", "传统"]),
            "season": "all",
            "calories": 320,
            "protein": 10.0,
            "carbs": 48.0,
            "fat": 10.0,
            "fiber": 2.0
        },
        {
            "name": "牛奶麦片",
            "category": "breakfast",
            "ingredients": json.dumps(["即食麦片:40g", "牛奶:200ml", "坚果:10g", "蜂蜜:5g"]),
            "steps": json.dumps(["麦片放入碗中", "热牛奶冲泡", "加入坚果", "微凉后加蜂蜜"]),
            "cost": 8.0,
            "difficulty": 1,
            "gi_value": 40,
            "cook_time": 5,
            "nutrition_tags": json.dumps(["低GI", "高钙", "快捷", "营养"]),
            "season": "all",
            "calories": 260,
            "protein": 12.0,
            "carbs": 36.0,
            "fat": 8.0,
            "fiber": 4.0
        },
        {
            "name": "素包子",
            "category": "breakfast",
            "ingredients": json.dumps(["面粉:200g", "酵母:3g", "粉丝:50g", "鸡蛋:2个", "青菜:100g", "盐:3g"]),
            "steps": json.dumps(["酵母温水化开", "面粉揉成面团发酵1小时", "粉丝泡软切碎", "鸡蛋炒散", "青菜焯水切碎", "混合馅料调味", "包包子蒸15分钟"]),
            "cost": 12.0,
            "difficulty": 3,
            "gi_value": 50,
            "cook_time": 90,
            "nutrition_tags": json.dumps(["粗粮搭配", "素食", "传统"]),
            "season": "all",
            "calories": 380,
            "protein": 14.0,
            "carbs": 65.0,
            "fat": 8.0,
            "fiber": 4.0
        },
        {
            "name": "红枣银耳羹",
            "category": "breakfast",
            "ingredients": json.dumps(["银耳:10g", "红枣:5颗", "枸杞:3g", "冰糖:10g", "水:500ml"]),
            "steps": json.dumps(["银耳泡发撕小朵", "红枣洗净", "一起放入锅中", "加水煮1小时", "加枸杞冰糖"]),
            "cost": 10.0,
            "difficulty": 1,
            "gi_value": 35,
            "cook_time": 70,
            "nutrition_tags": json.dumps(["美容", "滋阴", "润肺", "甜品"]),
            "season": "all",
            "calories": 180,
            "protein": 2.0,
            "carbs": 42.0,
            "fat": 0.5,
            "fiber": 3.0
        },
        {
            "name": "芹菜香干",
            "category": "lunch",
            "ingredients": json.dumps(["芹菜:150g", "香干:100g", "肉丝:50g", "蒜:3g", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["芹菜切段", "香干切片", "肉丝滑炒盛出", "另起锅炒芹菜", "加香干肉丝", "盐调味翻炒"]),
            "cost": 12.0,
            "difficulty": 1,
            "gi_value": 20,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "高纤维", "家常"]),
            "season": "all",
            "calories": 220,
            "protein": 16.0,
            "carbs": 10.0,
            "fat": 14.0,
            "fiber": 4.0
        },
        {
            "name": "宫保鸡丁",
            "category": "lunch",
            "ingredients": json.dumps(["鸡胸肉:150g", "花生:30g", "干辣椒:5g", "葱:10g", "蒜:3g", "酱油:10ml", "醋:5ml", "糖:5g"]),
            "steps": json.dumps(["鸡胸肉切丁", "调酱汁酱油醋糖", "花生干辣椒炒香", "鸡丁滑炒", "加入调料翻炒", "撒花生出锅"]),
            "cost": 20.0,
            "difficulty": 2,
            "gi_value": 25,
            "cook_time": 25,
            "nutrition_tags": json.dumps(["高蛋白", "家常", "下饭"]),
            "season": "all",
            "calories": 320,
            "protein": 30.0,
            "carbs": 18.0,
            "fat": 14.0,
            "fiber": 2.0
        },
        {
            "name": "酸辣土豆丝",
            "category": "lunch",
            "ingredients": json.dumps(["土豆:200g", "干辣椒:3g", "醋:10ml", "蒜:3g", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["土豆切丝泡水", "热油爆香蒜辣椒", "土豆丝沥干下锅", "大火快炒", "淋醋加盐", "保持脆感出锅"]),
            "cost": 6.0,
            "difficulty": 1,
            "gi_value": 45,
            "cook_time": 12,
            "nutrition_tags": json.dumps(["家常", "开胃", "素菜"]),
            "season": "all",
            "calories": 180,
            "protein": 4.0,
            "carbs": 32.0,
            "fat": 5.0,
            "fiber": 4.0
        },
        {
            "name": "萝卜炖牛肉",
            "category": "lunch",
            "ingredients": json.dumps(["牛肉:150g", "白萝卜:200g", "姜:5g", "八角:2个", "盐:3g", "酱油:10ml"]),
            "steps": json.dumps(["牛肉切块焯水", "萝卜切块", "牛肉姜片八角入锅", "加酱油翻炒", "加水炖1小时", "加萝卜再炖30分钟", "加盐调味"]),
            "cost": 40.0,
            "difficulty": 2,
            "gi_value": 25,
            "cook_time": 100,
            "nutrition_tags": json.dumps(["高蛋白", "暖身", "滋补", "冬季"]),
            "season": "winter",
            "calories": 380,
            "protein": 35.0,
            "carbs": 20.0,
            "fat": 18.0,
            "fiber": 4.0
        },
        {
            "name": "蚝油生菜",
            "category": "lunch",
            "ingredients": json.dumps(["生菜:200g", "蚝油:15ml", "蒜:3g", "油:5ml"]),
            "steps": json.dumps(["生菜洗净", "沸水焯烫10秒", "捞出摆盘", "蒜末蚝油加热", "淋在生菜上"]),
            "cost": 6.0,
            "difficulty": 1,
            "gi_value": 15,
            "cook_time": 8,
            "nutrition_tags": json.dumps(["低GI", "清淡", "快捷", "减肥"]),
            "season": "all",
            "calories": 100,
            "protein": 3.0,
            "carbs": 8.0,
            "fat": 5.0,
            "fiber": 4.0
        },
        {
            "name": "鱼香茄子",
            "category": "lunch",
            "ingredients": json.dumps(["茄子:200g", "肉末:50g", "豆瓣酱:10g", "蒜:3g", "葱:5g", "醋:5ml", "糖:5g", "油:15ml"]),
            "steps": json.dumps(["茄子切条", "肉末炒散", "另起油炸茄子", "捞出沥油", "锅底油炒豆瓣酱蒜末", "加肉末茄子", "醋糖调味翻炒"]),
            "cost": 12.0,
            "difficulty": 2,
            "gi_value": 20,
            "cook_time": 25,
            "nutrition_tags": json.dumps(["家常", "下饭", "开胃"]),
            "season": "all",
            "calories": 280,
            "protein": 12.0,
            "carbs": 22.0,
            "fat": 16.0,
            "fiber": 5.0
        },
        {
            "name": "苦瓜炒蛋",
            "category": "dinner",
            "ingredients": json.dumps(["苦瓜:150g", "鸡蛋:2个", "盐:2g", "油:10ml", "糖:3g"]),
            "steps": json.dumps(["苦瓜切片焯水", "鸡蛋打散", "热油炒鸡蛋盛出", "苦瓜翻炒", "加鸡蛋", "盐糖调味"]),
            "cost": 10.0,
            "difficulty": 1,
            "gi_value": 20,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "清热", "降火", "夏季"]),
            "season": "summer",
            "calories": 200,
            "protein": 14.0,
            "carbs": 8.0,
            "fat": 12.0,
            "fiber": 3.0
        },
        {
            "name": "冬瓜排骨汤",
            "category": "dinner",
            "ingredients": json.dumps(["冬瓜:200g", "排骨:100g", "姜:3g", "盐:2g"]),
            "steps": json.dumps(["排骨焯水", "冬瓜切块", "排骨姜片入锅", "加水炖40分钟", "加冬瓜再炖20分钟", "加盐调味"]),
            "cost": 28.0,
            "difficulty": 2,
            "gi_value": 15,
            "cook_time": 70,
            "nutrition_tags": json.dumps(["低GI", "清淡", "利尿", "夏季"]),
            "season": "summer",
            "calories": 280,
            "protein": 20.0,
            "carbs": 10.0,
            "fat": 18.0,
            "fiber": 2.0
        },
        {
            "name": "清蒸鸡腿肉",
            "category": "dinner",
            "ingredients": json.dumps(["鸡腿肉:200g", "姜:5g", "葱:5g", "料酒:10ml", "蒸鱼豉油:15ml"]),
            "steps": json.dumps(["鸡腿肉切块", "姜丝葱段铺底", "鸡肉放上面", "料酒去腥", "大火蒸15分钟", "淋蒸鱼豉油", "热油浇一下"]),
            "cost": 22.0,
            "difficulty": 1,
            "gi_value": 0,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "清淡", "健身"]),
            "season": "all",
            "calories": 220,
            "protein": 38.0,
            "carbs": 3.0,
            "fat": 6.0,
            "fiber": 0.5
        },
        {
            "name": "菠菜猪肝汤",
            "category": "dinner",
            "ingredients": json.dumps(["菠菜:100g", "猪肝:50g", "姜:3g", "盐:2g", "淀粉:5g"]),
            "steps": json.dumps(["猪肝切片浸泡", "菠菜洗净", "猪肝加淀粉抓匀", "锅中烧水", "先放姜片猪肝", "再放菠菜", "加盐调味"]),
            "cost": 15.0,
            "difficulty": 2,
            "gi_value": 15,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["低GI", "补铁", "补血", "明目"]),
            "season": "all",
            "calories": 160,
            "protein": 18.0,
            "carbs": 4.0,
            "fat": 8.0,
            "fiber": 3.0
        },
        {
            "name": "鲫鱼豆腐汤",
            "category": "dinner",
            "ingredients": json.dumps(["鲫鱼:200g", "豆腐:100g", "姜:5g", "葱:5g", "盐:2g", "料酒:10ml"]),
            "steps": json.dumps(["鲫鱼处理干净", "豆腐切块", "热油煎鱼至两面金黄", "加料酒姜片", "加水煮开", "放入豆腐", "小火炖20分钟", "加盐葱花"]),
            "cost": 20.0,
            "difficulty": 2,
            "gi_value": 15,
            "cook_time": 35,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "补钙", "滋补"]),
            "season": "all",
            "calories": 260,
            "protein": 30.0,
            "carbs": 8.0,
            "fat": 12.0,
            "fiber": 1.0
        },
        {
            "name": "凉拌木耳",
            "category": "dinner",
            "ingredients": json.dumps(["木耳:50g", "洋葱:30g", "香菜:10g", "蒜:3g", "醋:10ml", "酱油:5ml", "香油:3ml"]),
            "steps": json.dumps(["木耳泡发撕小朵", "洋葱切丝", "木耳焯水过凉", "混合食材", "调料汁拌匀", "冰箱冷藏更佳"]),
            "cost": 8.0,
            "difficulty": 1,
            "gi_value": 20,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "清血管", "排毒", "夏季"]),
            "season": "summer",
            "calories": 120,
            "protein": 3.0,
            "carbs": 12.0,
            "fat": 6.0,
            "fiber": 5.0
        },
        {
            "name": "荷塘小炒",
            "category": "dinner",
            "ingredients": json.dumps(["莲藕:50g", "荷兰豆:50g", "木耳:30g", "胡萝卜:30g", "蒜:3g", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["莲藕胡萝卜切片", "荷兰豆去筋", "木耳泡发", "沸水焯烫", "热油爆香蒜末", "所有食材翻炒", "加盐调味"]),
            "cost": 12.0,
            "difficulty": 1,
            "gi_value": 25,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "色彩丰富", "清爽"]),
            "season": "spring",
            "calories": 150,
            "protein": 4.0,
            "carbs": 20.0,
            "fat": 6.0,
            "fiber": 5.0
        },
        {
            "name": "香菇油菜",
            "category": "dinner",
            "ingredients": json.dumps(["香菇:50g", "油菜:150g", "蒜:3g", "油:10ml", "盐:2g", "蚝油:10ml"]),
            "steps": json.dumps(["香菇切片", "油菜洗净", "油菜焯水摆盘", "热油炒香菇", "加蚝油翻炒", "盛出放油菜上"]),
            "cost": 10.0,
            "difficulty": 1,
            "gi_value": 20,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "素食", "家常"]),
            "season": "all",
            "calories": 140,
            "protein": 5.0,
            "carbs": 12.0,
            "fat": 8.0,
            "fiber": 5.0
        },
        {
            "name": "腐竹烧肉",
            "category": "dinner",
            "ingredients": json.dumps(["五花肉:100g", "腐竹:50g", "酱油:15ml", "糖:5g", "葱姜:5g", "油:10ml"]),
            "steps": json.dumps(["腐竹泡软切段", "五花肉切块", "热油炒五花肉", "加酱油糖", "加水焖煮", "放腐竹再焖", "收汁出锅"]),
            "cost": 20.0,
            "difficulty": 2,
            "gi_value": 25,
            "cook_time": 40,
            "nutrition_tags": json.dumps(["高蛋白", "家常", "下饭"]),
            "season": "all",
            "calories": 380,
            "protein": 18.0,
            "carbs": 15.0,
            "fat": 28.0,
            "fiber": 2.0
        },
        {
            "name": "紫菜蛋花汤",
            "category": "dinner",
            "ingredients": json.dumps(["紫菜:10g", "鸡蛋:1个", "虾皮:5g", "盐:2g", "香油:2ml"]),
            "steps": json.dumps(["紫菜撕碎", "鸡蛋打散", "锅中烧水", "放入紫菜虾皮", "淋入蛋液", "加盐香油"]),
            "cost": 4.0,
            "difficulty": 1,
            "gi_value": 15,
            "cook_time": 8,
            "nutrition_tags": json.dumps(["低GI", "补碘", "补钙", "快捷"]),
            "season": "all",
            "calories": 90,
            "protein": 8.0,
            "carbs": 5.0,
            "fat": 4.0,
            "fiber": 2.0
        },
        {
            "name": "蒸蛋羹",
            "category": "breakfast",
            "ingredients": json.dumps(["鸡蛋:2个", "温水:150ml", "盐:2g", "生抽:3ml", "香油:2ml"]),
            "steps": json.dumps(["鸡蛋打散", "加温水盐搅匀", "撇去泡沫", "盖保鲜膜", "上锅蒸10分钟", "淋生抽香油"]),
            "cost": 4.0,
            "difficulty": 1,
            "gi_value": 10,
            "cook_time": 15,
            "nutrition_tags": json.dumps(["低GI", "高蛋白", "嫩滑", "易消化"]),
            "season": "all",
            "calories": 150,
            "protein": 14.0,
            "carbs": 3.0,
            "fat": 9.0,
            "fiber": 0.0
        },
        {
            "name": "红薯玉米粥",
            "category": "breakfast",
            "ingredients": json.dumps(["红薯:100g", "玉米面:30g", "水:400ml"]),
            "steps": json.dumps(["红薯去皮切块", "玉米面加水调匀", "锅中加水红薯", "煮开后倒入玉米面水", "不停搅拌煮熟"]),
            "cost": 5.0,
            "difficulty": 1,
            "gi_value": 42,
            "cook_time": 25,
            "nutrition_tags": json.dumps(["低GI", "粗粮", "饱腹", "通便"]),
            "season": "all",
            "calories": 180,
            "protein": 4.0,
            "carbs": 38.0,
            "fat": 1.5,
            "fiber": 4.0
        },
        {
            "name": "豆浆",
            "category": "breakfast",
            "ingredients": json.dumps(["黄豆:50g", "水:500ml", "糖:10g"]),
            "steps": json.dumps(["黄豆提前浸泡6小时", "放入豆浆机", "加水启动", "过滤豆渣", "加糖饮用"]),
            "cost": 5.0,
            "difficulty": 1,
            "gi_value": 15,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["植物蛋白", "补钙", "传统", "健康"]),
            "season": "all",
            "calories": 120,
            "protein": 10.0,
            "carbs": 10.0,
            "fat": 5.0,
            "fiber": 3.0
        },
        {
            "name": "蔬菜沙拉",
            "category": "lunch",
            "ingredients": json.dumps(["生菜:50g", "黄瓜:50g", "番茄:50g", "玉米粒:30g", "沙拉酱:20g"]),
            "steps": json.dumps(["所有蔬菜洗净切好", "玉米粒焯熟", "混合放入碗中", "淋上沙拉酱"]),
            "cost": 10.0,
            "difficulty": 1,
            "gi_value": 20,
            "cook_time": 10,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "减肥", "清爽"]),
            "season": "summer",
            "calories": 180,
            "protein": 4.0,
            "carbs": 15.0,
            "fat": 12.0,
            "fiber": 4.0
        },
        {
            "name": "糖醋里脊",
            "category": "lunch",
            "ingredients": json.dumps(["里脊肉:150g", "番茄酱:30g", "醋:15ml", "糖:15g", "淀粉:20g", "油:200ml"]),
            "steps": json.dumps(["里脊切条", "裹淀粉", "油炸至金黄", "另起锅调糖醋汁", "番茄酱醋糖混合", "放入肉条翻炒", "挂匀汁出锅"]),
            "cost": 22.0,
            "difficulty": 2,
            "gi_value": 35,
            "cook_time": 30,
            "nutrition_tags": json.dumps(["家常", "酸甜", "下饭", "孩子爱吃"]),
            "season": "all",
            "calories": 420,
            "protein": 25.0,
            "carbs": 38.0,
            "fat": 18.0,
            "fiber": 1.0
        },
        {
            "name": "干煸四季豆",
            "category": "lunch",
            "ingredients": json.dumps(["四季豆:200g", "肉末:50g", "干辣椒:5g", "蒜:3g", "油:10ml", "盐:2g"]),
            "steps": json.dumps(["四季豆去筋切段", "热油煸四季豆至起皱", "盛出备用", "另起锅炒肉末", "加干辣椒蒜末", "四季豆回锅", "加盐翻炒"]),
            "cost": 10.0,
            "difficulty": 2,
            "gi_value": 25,
            "cook_time": 20,
            "nutrition_tags": json.dumps(["低GI", "高纤维", "家常", "下饭"]),
            "season": "all",
            "calories": 200,
            "protein": 12.0,
            "carbs": 15.0,
            "fat": 12.0,
            "fiber": 5.0
        },
        {
            "name": "板栗烧鸡",
            "category": "dinner",
            "ingredients": json.dumps(["鸡肉:200g", "板栗:100g", "酱油:15ml", "糖:5g", "姜:5g", "油:10ml"]),
            "steps": json.dumps(["鸡肉切块", "板栗去壳", "热油炒鸡肉", "加酱油糖姜", "加水没过鸡肉", "放入板栗", "焖煮30分钟", "收汁"]),
            "cost": 35.0,
            "difficulty": 2,
            "gi_value": 25,
            "cook_time": 50,
            "nutrition_tags": json.dumps(["高蛋白", "滋补", "秋冬", "香甜"]),
            "season": "autumn",
            "calories": 380,
            "protein": 32.0,
            "carbs": 25.0,
            "fat": 16.0,
            "fiber": 3.0
        },
        {
            "name": "银耳雪梨汤",
            "category": "dinner",
            "ingredients": json.dumps(["银耳:10g", "雪梨:1个", "冰糖:10g", "枸杞:3g", "水:500ml"]),
            "steps": json.dumps(["银耳泡发撕小朵", "雪梨去皮切块", "银耳先煮30分钟", "加雪梨冰糖", "再煮20分钟", "加枸杞"]),
            "cost": 12.0,
            "difficulty": 1,
            "gi_value": 30,
            "cook_time": 60,
            "nutrition_tags": json.dumps(["润肺", "止咳", "美容", "甜品"]),
            "season": "autumn",
            "calories": 160,
            "protein": 2.0,
            "carbs": 38.0,
            "fat": 0.5,
            "fiber": 3.0
        },
        {
            "name": "羊肉火锅",
            "category": "dinner",
            "ingredients": json.dumps(["羊肉:300g", "各种蔬菜:500g", "火锅底料:50g", "蘸料:适量"]),
            "steps": json.dumps(["准备各种蔬菜", "羊肉切片", "火锅底料加水煮开", "涮肉涮菜", "蘸料食用"]),
            "cost": 80.0,
            "difficulty": 2,
            "gi_value": 20,
            "cook_time": 60,
            "nutrition_tags": json.dumps(["高蛋白", "暖身", "冬季", "聚会"]),
            "season": "winter",
            "calories": 450,
            "protein": 40.0,
            "carbs": 25.0,
            "fat": 22.0,
            "fiber": 6.0
        }
    ]

    for recipe in recipes:
        c.execute('''
            INSERT INTO recipes (name, category, ingredients, steps, cost, difficulty, gi_value, cook_time, nutrition_tags, season, calories, protein, carbs, fat, fiber)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            recipe['name'],
            recipe['category'],
            recipe['ingredients'],
            recipe['steps'],
            recipe['cost'],
            recipe['difficulty'],
            recipe['gi_value'],
            recipe['cook_time'],
            recipe['nutrition_tags'],
            recipe['season'],
            recipe['calories'],
            recipe['protein'],
            recipe['carbs'],
            recipe['fat'],
            recipe['fiber']
        ))

if __name__ == '__main__':
    init_db()
    print("数据库初始化完成！")